name: Playwright Pytest CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      # 🔹 Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔹 Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 🔹 Create virtual environment & install deps
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 🔹 Install Playwright browsers
      - name: Install Playwright Browsers
        run: |
          source .venv/bin/activate
          playwright install --with-deps

      # 🔹 Run tests in parallel
      - name: Run Pytest
        run: |
          source .venv/bin/activate

          rm -rf html_reports allure-results
          mkdir -p html_reports allure-results

          pytest -n 3 -v -s \
          --maxfail=1 \
          --alluredir=allure-results \
          --html=html_reports/test_report.html

      # 🔹 Upload HTML report
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: html_reports/

      # 🔹 Upload Allure results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/